<div class="row">
    <div class="col-md-6 col-md-offset-3 text-center">
        <h1>Simple Chat Test Project</h1>

            <?php
                $form->setAttributes([
                    'action' => $this->url('home', ['action' => 'add']),
                    'class' => ' text-center',
                    'id' => 'chat-form'
                ]);
                $form->prepare();
            ?>

            <?= $this->form()->openTag($form) ?>

            <div class="row">
                <div class="text-field col-sm-10 col-xs-9">
                    <?= $this->formRow($form->get('text')) ?>
                </div>

                <div class="col-sm-2 col-xs-3 text-right">
                    <?= $this->formSubmit($form->get('submit')) ?>
                </div>
            </div>

            <?= $this->form()->closeTag() ?>
    </div>

    <div class="col-md-12">
        <div class="table-messages">
            <table class="table">
                <thead>
                <tr>
                    <th>Created</th>
                    <th>Text</th>
                </tr>
                </thead>
                <tbody>
                <?php foreach ($messages as $message) : ?>
                    <tr>
                        <td class="col-xs-6 col-sm-4"><?= $this->escapeHtml($message->created) ?></td>
                        <td class="col-xs-6 col-sm-8"><?= $this->escapeHtml($message->text) ?></td>
                    </tr>
                <?php endforeach; ?>
                </tbody>
            </table>
        </div>
    </div>
</div>
