<div class="row">
    <div class="col-md-6 col-md-offset-3 text-center">
        <h1>Simple Chat Test Project</h1>

        <?php
            $form->setAttributes([
                'action' => $this->url('home', ['action' => 'add']),
                'class' => 'form-inline text-center',
                'id' => 'chat-form'
            ]);
            $form->prepare();

            echo $this->form()->openTag($form);
            ?>
            <div class="form-group">
                <?= $this->formRow($form->get('text')) ?>
            </div>

            <?php
            echo $this->formSubmit($form->get('submit'));
            echo $this->form()->closeTag();
        ?>
    </div>

    <div class="col-md-12">
        <table class="table">
            <thead>
                <tr>
                    <th>Created</th>
                    <th>Text</th>
                </tr>
            </thead>
            <tbody>
                <?php foreach ($messages as $message) : ?>
                    <tr>
                        <td class="col-xs-6 col-sm-4"><?= $this->escapeHtml($message->created) ?></td>
                        <td class="col-xs-6 col-sm-8"><?= $this->escapeHtml($message->text) ?></td>
                    </tr>
                <?php endforeach; ?>
            </tbody>
        </table>

    </div>
</div>
