<div class="row">
    <div class="col-md-6 col-md-offset-3 text-center">
        <h1>Simple Chat Test Project</h1>
    </div>

    <div class="col-md-12">
        <table class="table">
            <thead>
                <tr>
                    <th>Created</th>
                    <th>Text</th>
                </tr>
            </thead>
            <tbody>
                <?php foreach ($messages as $message) : ?>
                    <tr>
                        <td class="col-xs-6 col-sm-4"><?= $this->escapeHtml($message->created) ?></td>
                        <td class="col-xs-6 col-sm-8"><?= $this->escapeHtml($message->text) ?></td>
                    </tr>
                <?php endforeach; ?>
            </tbody>
        </table>

    </div>
</div>
